---
- name: add nginx release repo
  shell: rpm -Uvh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm creates=/etc/yum.repos.d/nginx.repo
  tags: nginx

- name: install nginx
  yum: name=nginx state=present
  tags: nginx

- name: add nginx php configuration
  template: src=php.conf.j2 dest=/etc/nginx/php.conf
  tags: nginx

- name: backup default nginx configuration
  shell: cp /etc/nginx/nginx.conf /etc/nginx/default.nginx.conf creates=/etc/nginx/default.nginx.conf
  tags: nginx

- name: configure nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  tags: nginx
  notify:
    - reload nginx

- name: add sites configuration
  template: src=laravel.conf.j2 dest=/etc/nginx/conf.d/{{item.title}}.conf
  with_items: nginx.sites
  notify:
  - reload nginx
  tags: nginx

- name: run nginx
  service: name=nginx state=running enabled=yes
  tags: nginx
